---
# tasks file for create_empty_file
- name: Create directory
  ansible.builtin.file:
    path: /etc/iaas
    state: directory
    mode: '0755'

- name: Create empty file with permissions
  ansible.builtin.file:
    path: /etc/iaas/testfile
    state: touch
    mode: '0500'
    owner: george
